### ISSUE TITLE
wire switches to ground instead of Vcc

### ISSUE THREAD

**Issue by wolfwood** [akaenner/picosplit#1]
Hi! I'm also a fan of direct wired switches instead of matrixes for split keyboards.

i wanted to suggest wiring switches to ground instead of Vcc.  With a gpio input you can detect a connection to ground as easily as to the supply voltage, and this will lower your power draw and EM emissions, and reduce the chances of running a current through someone who decides to touch the wiring when it's plugged in :)

**Comment by akaenner** [comment]
Of course you are right. Since my first tests with only one button, I have stuck with the wiring. I should have changed that at some point and I will now implement your suggestion. It will take a few days, because I have to adapt the documentation and that is most of the work.
